# Generated by Django 6.0 on 2026-07-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='claim_type',
            field=models.CharField(choices=[('DISTRIBUTION', 'Distribution Event'), ('WALK_IN', 'Walk-in / Office Visit')], default='DISTRIBUTION', max_length=20),
        ),
    ]
