# Generated by Django 6.0 on 2026-07-16 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_aidclaim_claim_type'),
        ('households', '0015_floodpronearea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidschedule',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='per_beneficiary_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='GeneratedBeneficiaryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('prioritization_strategy_used', models.CharField(max_length=30)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_list', to='distribution.aidschedule')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_manually', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='households.family')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('beneficiary_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='distribution.generatedbeneficiarylist')),
            ],
        ),
    ]
