# Generated by Django 6.0 on 2026-07-17 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_aidschedule_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidschedule',
            name='end_datetime',
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'All Beneficiaries Claimed'), ('FORCED', 'Manually Ended (Incomplete)')], max_length=20),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='finished_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
