# Generated by Django 6.0 on 2026-07-18 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_place_user_citizenship_user_civil_status_and_more'),
        ('distribution', '0004_remove_aidschedule_end_datetime_and_more'),
        ('households', '0015_floodpronearea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='distribution.aidschedule')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_assignments', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Optional — leave blank if staff is assigned to the whole barangay, not a specific zone.', null=True, on_delete=django.db.models.deletion.CASCADE, to='households.zone')),
            ],
            options={
                'unique_together': {('schedule', 'staff', 'barangay', 'zone')},
            },
        ),
    ]
