# Generated by Django 6.0 on 2026-07-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_place_user_citizenship_user_civil_status_and_more'),
        ('distribution', '0005_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='barangay',
            field=models.ForeignKey(blank=True, help_text='Optional — leave blank for municipal-wide assignment (all barangays).', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay'),
        ),
    ]
