# Generated by Django 6.0 on 2026-08-03 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_alter_assignedto_barangay'),
        ('households', '0016_add_unique_constraint_to_rfid_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedbeneficiary',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='Required for individual-based assistance to specify which member was selected', null=True, on_delete=django.db.models.deletion.SET_NULL, to='households.familymember'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'All Beneficiaries Claimed'), ('FORCED', 'Manually Ended (Incomplete)'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
