# Generated by Django 6.0 on 2026-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_aidschedule_created_by_aidschedule_last_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidschedule',
            name='prioritization_strategy',
            field=models.CharField(choices=[('LOWEST_INCOME_FIRST', 'Lowest Income First'), ('TYPHOON_PRIORITY', 'Typhoon/Vulnerability Priority'), ('DAYS_SINCE_LAST_ASSISTANCE', 'Longest Time Since Last Assistance'), ('SPECIAL_CATEGORY', 'Special Category (PWD/Senior/Solo Parent)')], default='LOWEST_INCOME_FIRST', help_text='Strategy used to rank eligible beneficiaries when generating the beneficiary list.', max_length=30),
        ),
    ]
