# Generated by Django 6.0 on 2026-08-10 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_place_user_citizenship_user_civil_status_and_more'),
        ('distribution', '0009_add_prioritization_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidschedule',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitude coordinate of the distribution location', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitude coordinate of the distribution location', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DistributionVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Venue name (e.g., Santa Rita Town Plaza)', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Active venues appear in location picker. Deactivate instead of deleting to preserve history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(blank=True, help_text='Associated barangay (optional - some venues like town plaza are municipal-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.barangay')),
            ],
            options={
                'verbose_name': 'Distribution Venue',
                'verbose_name_plural': 'Distribution Venues',
                'ordering': ['name'],
            },
        ),
    ]
