# Generated by Django 6.0 on 2026-08-10 10:31

from django.db import migrations
from decimal import Decimal


def seed_venues(apps, schema_editor):
    """Seed initial distribution venues with placeholder coordinates.
    
    NOTE: These coordinates are PLACEHOLDERS and must be updated with
    accurate lat/lng values before deployment. The user will supply
    the exact coordinates for each venue.
    """
    DistributionVenue = apps.get_model('distribution', 'DistributionVenue')
    Barangay = apps.get_model('accounts', 'Barangay')
    
    # Get barangays (will be None if not found, which is acceptable for municipal-wide venues)
    try:
        becuran = Barangay.objects.get(name='Becuran')
    except Barangay.DoesNotExist:
        becuran = None
    
    try:
        dila_dila = Barangay.objects.get(name='Dila-Dila')
    except Barangay.DoesNotExist:
        dila_dila = None
    
    try:
        san_matias = Barangay.objects.get(name='San Matias')
    except Barangay.DoesNotExist:
        san_matias = None
    
    try:
        santa_monica = Barangay.objects.get(name='Santa Monica')
    except Barangay.DoesNotExist:
        santa_monica = None
    
    try:
        san_basilio = Barangay.objects.get(name='San Basilio')
    except Barangay.DoesNotExist:
        san_basilio = None
    
    try:
        san_juan = Barangay.objects.get(name='San Juan')
    except Barangay.DoesNotExist:
        san_juan = None
    
    try:
        san_agustin = Barangay.objects.get(name='San Agustin')
    except Barangay.DoesNotExist:
        san_agustin = None
    
    try:
        san_isidro = Barangay.objects.get(name='San Isidro')
    except Barangay.DoesNotExist:
        san_isidro = None
    
    # Accurate coordinates for Santa Rita, Pampanga venues
    venues = [
        {
            'name': 'Santa Rita Town Plaza',
            'latitude': Decimal('15.000282968104935'),
            'longitude': Decimal('120.61762685746417'),
            'barangay': None,  # Municipal-wide venue
        },
        {
            'name': 'Becuran Covered Court',
            'latitude': Decimal('15.010863700184911'),
            'longitude': Decimal('120.59282845459575'),
            'barangay': becuran,
        },
        {
            'name': 'Dila-Dila Sports Center',
            'latitude': Decimal('15.0148058154301'),
            'longitude': Decimal('120.5841427813036'),
            'barangay': dila_dila,
        },
        {
            'name': 'San Matias Covered Court',
            'latitude': Decimal('15.004883035433659'),
            'longitude': Decimal('120.60409977344354'),
            'barangay': san_matias,
        },
        {
            'name': 'Santa Monica Covered Court',
            'latitude': Decimal('14.993409148463142'),
            'longitude': Decimal('120.61080907785987'),
            'barangay': santa_monica,
        },
        {
            'name': 'San Agustin Covered Court',
            'latitude': Decimal('14.99003305495033'),
            'longitude': Decimal('120.60571289340767'),
            'barangay': san_agustin,
        },
        {
            'name': 'San Basilio Covered Court',
            'latitude': Decimal('15.036582049910601'),
            'longitude': Decimal('120.58042984467966'),
            'barangay': san_basilio,
        },
        {
            'name': 'San Isidro Covered Court',
            'latitude': Decimal('15.00790592447443'),
            'longitude': Decimal('120.6116201755792'),
            'barangay': san_isidro,
        },
        {
            'name': 'San Juan Covered Court',
            'latitude': Decimal('15.0079034343082'),
            'longitude': Decimal('120.62330052870767'),
            'barangay': san_juan,
        },
    ]
    
    for venue_data in venues:
        DistributionVenue.objects.create(**venue_data)


def reverse_seed_venues(apps, schema_editor):
    """Reverse the seeding by deleting all venues."""
    DistributionVenue = apps.get_model('distribution', 'DistributionVenue')
    DistributionVenue.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_aidschedule_location_lat_aidschedule_location_lng_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_venues, reverse_seed_venues),
    ]
