# Generated by Django 6.0 on 2026-08-10 13:36

from django.db import migrations
from decimal import Decimal


def update_venue_coordinates(apps, schema_editor):
    """Update venue coordinates with accurate values and rename venues."""
    DistributionVenue = apps.get_model('distribution', 'DistributionVenue')
    
    # Update existing venues with accurate coordinates
    # Note: This migration is for databases that already have the old placeholder coordinates
    # New databases will get the correct coordinates directly from migration 0011
    venue_updates = {
        'Santa Rita Town Plaza': (Decimal('15.000282968104935'), Decimal('120.61762685746417')),
        'Becuran Sports Center': (Decimal('15.010863700184911'), Decimal('120.59282845459575')),
        'Dila-Dila Barangay Plaza': (Decimal('15.0148058154301'), Decimal('120.5841427813036')),
        'San Matias Covered Court': (Decimal('15.004883035433659'), Decimal('120.60409977344354')),
        'Santa Monica Covered Court': (Decimal('14.993409148463142'), Decimal('120.61080907785987')),
        'San Basilio Covered Court': (Decimal('15.036582049910601'), Decimal('120.58042984467966')),
        'San Juan Covered Court': (Decimal('15.0079034343082'), Decimal('120.62330052870767')),
    }
    
    for name, (lat, lng) in venue_updates.items():
        DistributionVenue.objects.filter(name=name).update(latitude=lat, longitude=lng)
    
    # Rename venues to match actual names
    DistributionVenue.objects.filter(name='Becuran Sports Center').update(name='Becuran Covered Court')
    DistributionVenue.objects.filter(name='Dila-Dila Barangay Plaza').update(name='Dila-Dila Sports Center')


def reverse_update_venue_coordinates(apps, schema_editor):
    """Reverse the coordinate updates by reverting names."""
    DistributionVenue = apps.get_model('distribution', 'DistributionVenue')
    
    # Rename back to original names
    DistributionVenue.objects.filter(name='Becuran Covered Court').update(name='Becuran Sports Center')
    DistributionVenue.objects.filter(name='Dila-Dila Sports Center').update(name='Dila-Dila Barangay Plaza')


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_seed_distribution_venues'),
    ]

    operations = [
        migrations.RunPython(update_venue_coordinates, reverse_update_venue_coordinates),
    ]
