# Generated by Django 6.0 on 2026-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_update_venue_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount distributed to the beneficiary. Auto-filled from schedule.per_beneficiary_amount for scheduled claims, manually entered for walk-ins.', max_digits=12, null=True),
        ),
    ]
