# Generated by Django 6.0 on 2026-08-21 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_aidclaim_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='is_late_scheduled_claim',
            field=models.BooleanField(default=False, help_text='True if this walk-in claim fulfills a missed scheduled distribution within the 7-day grace period'),
        ),
        migrations.AddField(
            model_name='aidclaim',
            name='original_schedule',
            field=models.ForeignKey(blank=True, help_text='If is_late_scheduled_claim=True, links to the original missed schedule this claim fulfills', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_claims', to='distribution.aidschedule'),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='distribution.aidschedule'),
        ),
    ]
