# Generated by Django 6.0 on 2026-09-06 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0014_aidclaim_is_late_scheduled_claim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='True if this claim has been exported for offline reconciliation (prevents duplicate exports)'),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='claim_type',
            field=models.CharField(choices=[('DISTRIBUTION', 'Distribution Event'), ('WALK_IN', 'Walk-in / Office Visit'), ('OFFLINE_IMPORT', 'Offline Reconciliation Import')], default='DISTRIBUTION', max_length=20),
        ),
        migrations.CreateModel(
            name='BeneficiaryBackupDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_updated_at_snapshot', models.DateTimeField()),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_downloads', to='distribution.aidschedule')),
            ],
            options={
                'verbose_name': 'Beneficiary Backup Download',
                'verbose_name_plural': 'Beneficiary Backup Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
