# Generated by Django 6.0 on 2026-09-06 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0015_aidclaim_is_exported_alter_aidclaim_claim_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('households_count', models.PositiveIntegerField(default=0)),
                ('programs_count', models.PositiveIntegerField(default=0)),
                ('claims_count', models.PositiveIntegerField(default=0)),
                ('synced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offline Sync Metadata',
                'verbose_name_plural': 'Offline Sync Metadata',
            },
        ),
    ]
