# Generated by Django 6.0 on 2026-08-03 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGOUT', 'Logout'), ('OTP_SUCCESS', 'OTP Verification Success'), ('OTP_FAILURE', 'OTP Verification Failure'), ('USER_CREATED', 'User Created'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_BARANGAY_CHANGED', 'User Barangay Assignment Changed'), ('SCHEDULE_CREATED', 'Schedule Created'), ('SCHEDULE_EDITED', 'Schedule Edited'), ('SCHEDULE_CANCELLED', 'Schedule Cancelled'), ('SCHEDULE_FORCE_FINISHED', 'Schedule Force Finished'), ('SCHEDULE_AUTO_FINISHED', 'Schedule Auto Finished'), ('BENEFICIARY_LIST_GENERATED', 'Beneficiary List Generated'), ('BENEFICIARY_MANUAL_ADD', 'Beneficiary Manual Override Add'), ('BENEFICIARY_MANUAL_REMOVE', 'Beneficiary Manual Override Remove'), ('CLAIM_RFID', 'RFID Claim Processed'), ('CLAIM_WALKIN', 'Walk-in Claim Processed'), ('ACCESS_DENIED_SCAN', 'Access Denied - Scan RFID'), ('ACCESS_DENIED_BENEFICIARY', 'Access Denied - Beneficiary List'), ('ACCESS_DENIED_SEARCH', 'Access Denied - Search Eligible'), ('ACCESS_DENIED_FINISH', 'Access Denied - Finish Distribution'), ('REPORT_GENERATED', 'Report Generated')], db_index=True, max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(help_text='Human-readable description of the action (do not include sensitive values like passwords/OTPs)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (null for anonymous failed login attempts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='core_auditl_action__9597a4_idx'), models.Index(fields=['actor', 'created_at'], name='core_auditl_actor_i_41600a_idx')],
            },
        ),
    ]
