# Generated by Django 6.0 on 2026-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure'), ('LOGOUT', 'Logout'), ('OTP_LOCKOUT', 'OTP Verification Lockout'), ('OTP_SUCCESS', 'OTP Verification Success'), ('OTP_FAILURE', 'OTP Verification Failure'), ('USER_CREATED', 'User Created'), ('USER_ACTIVATED', 'User Activated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_BARANGAY_CHANGED', 'User Barangay Assignment Changed'), ('SCHEDULE_CREATED', 'Schedule Created'), ('SCHEDULE_EDITED', 'Schedule Edited'), ('SCHEDULE_CANCELLED', 'Schedule Cancelled'), ('SCHEDULE_FORCE_FINISHED', 'Schedule Force Finished'), ('SCHEDULE_AUTO_FINISHED', 'Schedule Auto Finished'), ('BENEFICIARY_LIST_GENERATED', 'Beneficiary List Generated'), ('BENEFICIARY_MANUAL_ADD', 'Beneficiary Manual Override Add'), ('BENEFICIARY_MANUAL_REMOVE', 'Beneficiary Manual Override Remove'), ('CLAIM_RFID', 'RFID Claim Processed'), ('CLAIM_WALKIN', 'Walk-in Claim Processed'), ('ACCESS_DENIED_SCAN', 'Access Denied - Scan RFID'), ('ACCESS_DENIED_BENEFICIARY', 'Access Denied - Beneficiary List'), ('ACCESS_DENIED_SEARCH', 'Access Denied - Search Eligible'), ('ACCESS_DENIED_FINISH', 'Access Denied - Finish Distribution'), ('REPORT_GENERATED', 'Report Generated'), ('BENEFICIARY_BACKUP_DOWNLOADED', 'Beneficiary List Backup Downloaded'), ('BENEFICIARY_BACKUP_SKIPPED', 'Beneficiary List Backup Skipped'), ('OFFLINE_SYNC_EXPORTED', 'Offline Kit Sync Exported'), ('OFFLINE_CLAIM_RECONCILIATION_IMPORT', 'Offline Claim Reconciliation Import')], db_index=True, max_length=50),
        ),
    ]
