"""
Django settings for sara project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ═══════════════════════════════════════════════════════════════
# OTP/2FA CONFIGURATION
# ═══════════════════════════════════════════════════════════════
# IMPORTANT: OTP_ENABLED must be True (or unset) in production.
# This flag is intended ONLY for offline local development/testing without internet access.
# If this is False in a real deployment, authentication security is severely compromised.
# Set via environment variable: OTP_ENABLED=True (or omit to default to True)
# ═══════════════════════════════════════════════════════════════
OTP_ENABLED = os.getenv('OTP_ENABLED', 'True') == 'True'

if not OTP_ENABLED:
    logging.warning("⚠️ OTP IS DISABLED — this should never be true in production. This setting is for offline local development only.")

# ═══════════════════════════════════════════════════════════════
# OFFLINE MODE CONFIGURATION
# ═══════════════════════════════════════════════════════════════
# IMPORTANT: OFFLINE_MODE must be explicitly set to True ONLY on the offline field deployment.
# This flag enables destructive import operations that overwrite municipal data.
# If this is False (default), import views will refuse to run to protect production data.
# Set via environment variable: OFFLINE_MODE=True
# ═══════════════════════════════════════════════════════════════
OFFLINE_MODE = os.getenv('OFFLINE_MODE', 'False') == 'True'

if OFFLINE_MODE:
    logging.warning("⚠️ OFFLINE MODE IS ENABLED — destructive import operations are permitted. This should only be true on the offline field deployment.")

# ═══════════════════════════════════════════════════════════════
# PRODUCTION DATABASE PROTECTION
# ═══════════════════════════════════════════════════════════════
# IMPORTANT: PRODUCTION_DB_NAME should be set to the known production database name.
# Import views will refuse to run if the current database matches this name, even if OFFLINE_MODE=True.
# This provides defense-in-depth protection against accidental production database writes.
# Set via environment variable: PRODUCTION_DB_NAME=db.sqlite3 (or your production database name)
# ═══════════════════════════════════════════════════════════════
PRODUCTION_DB_NAME = os.getenv('PRODUCTION_DB_NAME', '')

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Allow override via environment variable for multi-instance deployments
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-tp#n=ywpr!4=ho!7^i3vs68lqm2@m_o&&m)!o+(u_wy-8lt9ui')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Session and CSRF cookie names - allow override for multi-instance deployments
SESSION_COOKIE_NAME = os.environ.get('SESSION_COOKIE_NAME', 'sessionid')
CSRF_COOKIE_NAME = os.environ.get('CSRF_COOKIE_NAME', 'csrftoken')

ALLOWED_HOSTS = [ '192.168.100.130', '10.230.245.161', '10.64.151.161', 'localhost', '127.0.0.1', '10.64.151.242', '192.168.1.17']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
    'households',
    'programs',
    'distribution',
    'rfid',
    'monitoring',
    'reports',
    'django_otp',
    'django_otp.plugins.otp_email',
    'django_otp.plugins.otp_totp',  # optional TOTP
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'sara.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.auth_required',
                'accounts.context_processors.offline_sync_metadata',
            ],
        },
    },
]

WSGI_APPLICATION = 'sara.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/login/'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',  # email-only login
]

#Brevo SMTP settings for email notifications
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') 
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'SRC Capstone System<dizonjelo50@gmail.com>'


# Email OTP config
#OTP_EMAIL_SENDER = 'noreply@yourdomain.com'
#OTP_EMAIL_SUBJECT = 'Your login verification code'
OTP_EMAIL_TOKEN_VALIDITY = 300  # 5 minutes
OTP_EMAIL_BODY_HTML_TEMPLATE_PATH = 'otp/otp_email.html'

# Password reset config
PASSWORD_RESET_TIMEOUT = 900  # 15 minutes (in seconds)

# Session settings for idle-based auto-logout
SESSION_COOKIE_AGE = 1800  # 30 minutes - global fallback/hard ceiling
SESSION_SAVE_EVERY_REQUEST = False  # Disabled - @session_protected decorator handles set_expiry() explicitly
SESSION_COOKIE_SECURE = not DEBUG  # True in production, False for local HTTP development
SESSION_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token