# Generated by Django 6.0 on 2026-01-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_family_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familymember'),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_claims', to='accounts.family'),
        ),
    ]
