# Generated by Django 6.0 on 2026-01-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_aidclaim_claimed_by_alter_aidclaim_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidclaim',
            name='claimed_by',
        ),
        migrations.AddField(
            model_name='aidclaim',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='For individual aids like Scholar/Senior', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familymember'),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.family'),
        ),
    ]
