# Generated by Django 6.0 on 2026-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_aidclaim_claimed_by_aidclaim_family_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.CharField(choices=[('RELIEF', 'Relief'), ('SCHOLAR', 'Scholar'), ('SENIOR', 'Senior')], max_length=20)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
            ],
        ),
    ]
