# Generated by Django 6.0 on 2026-05-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_aidoftheday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidclaim',
            name='aid_type',
            field=models.CharField(choices=[('RELIEF', 'Relief'), ('SENIOR', 'Senior Citizen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='For individual aids like Senior', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familymember'),
        ),
        migrations.AlterField(
            model_name='aidoftheday',
            name='aid_type',
            field=models.CharField(choices=[('RELIEF', 'Relief'), ('SENIOR', 'Senior')], max_length=20),
        ),
    ]
