# Generated by Django 6.0 on 2026-05-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_aidclaim_aid_type_alter_aidclaim_family_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_type', models.CharField(choices=[('RELIEF', 'Relief'), ('SENIOR', 'Senior Citizen')], max_length=20)),
                ('schedule_datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.barangay')),
            ],
        ),
        migrations.DeleteModel(
            name='AidOfTheDay',
        ),
    ]
