# Generated by Django 6.0 on 2026-05-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_aidschedule_delete_aidoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidschedule',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
