# Generated by Django 6.0 on 2026-05-04 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_aidschedule_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidschedule',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
