# Generated by Django 6.0 on 2026-05-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_aidschedule_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aidschedule'),
        ),
    ]
