# Generated by Django 6.0 on 2026-06-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_program_aidcategory_assistance'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidclaim',
            name='assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='accounts.assistance'),
        ),
        migrations.AddField(
            model_name='aidschedule',
            name='assistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='accounts.assistance'),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='aid_type',
            field=models.CharField(blank=True, choices=[('RELIEF', 'Relief'), ('SENIOR', 'Senior Citizen')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aidclaim',
            name='family_member',
            field=models.ForeignKey(blank=True, help_text='Required for individual-based assistance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.familymember'),
        ),
        migrations.AlterField(
            model_name='aidschedule',
            name='aid_type',
            field=models.CharField(blank=True, choices=[('RELIEF', 'Relief'), ('SENIOR', 'Senior Citizen')], max_length=20, null=True),
        ),
    ]
