# Generated by Django 6.0 on 2026-06-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_aidclaim_assistance_aidschedule_assistance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidclaim',
            name='aid_type',
        ),
        migrations.RemoveField(
            model_name='aidschedule',
            name='aid_type',
        ),
    ]
