# Generated by Django 6.0 on 2026-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportgenerationlog',
            name='report_type',
            field=models.CharField(choices=[('SUMMARY', 'Statistical Summary Report'), ('BENEFICIARY_LIST', 'Beneficiary List Report'), ('WALKIN_SUMMARY', 'Walk-in Summary Report'), ('WALKIN_BENEFICIARY_LIST', 'Walk-in Beneficiary List Report')], max_length=30),
        ),
    ]
