# Generated by Django 6.0 on 2026-06-27 07:54

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_solo_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.resident_profile_image_path),
        ),
    ]
