# Generated by Django 6.0 on 2026-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_familymember_is_pwd_familymember_is_solo_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='age',
        ),
        migrations.AddField(
            model_name='familymember',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_senior_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
