# Generated by Django 6.0 on 2026-06-30 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_remove_familymember_age_familymember_birthdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('HEAD', 'Head of Family'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SON_IN_LAW', 'Son-in-Law'), ('DAUGHTER_IN_LAW', 'Daughter-in-Law'), ('FATHER_IN_LAW', 'Father-in-Law'), ('MOTHER_IN_LAW', 'Mother-in-Law'), ('GRANDCHILD', 'Grandchild'), ('SIBLING', 'Sibling/Brother/Sister'), ('GRANDPARENT', 'Grandparent'), ('OTHER_RELATIVE', 'Other Relative'), ('NON_RELATIVE', 'Non-Relative/Boarder')], max_length=20),
        ),
        migrations.CreateModel(
            name='PWDProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('disability_type', models.CharField(blank=True, choices=[('Visual', 'Visual'), ('Hearing', 'Hearing'), ('Speech', 'Speech'), ('Orthopedic', 'Orthopedic'), ('Mental/Intellectual', 'Mental/Intellectual'), ('Psychosocial', 'Psychosocial'), ('Learning', 'Learning'), ('Chronic Illness/Rare Disease', 'Chronic Illness/Rare Disease')], max_length=50, null=True)),
                ('cause_of_disability', models.CharField(blank=True, choices=[('Congenital', 'Congenital'), ('Acquired-Illness', 'Acquired-Illness'), ('Acquired-Injury', 'Acquired-Injury'), ('Acquired-Workplace', 'Acquired-Workplace'), ('Other', 'Other')], max_length=50, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('certifying_physician', models.CharField(blank=True, max_length=100, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pwd_profile', to='households.familymember')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorCitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_attainment', models.CharField(blank=True, max_length=100, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('other_skills', models.CharField(blank=True, max_length=100, null=True)),
                ('ctc_no', models.CharField(blank=True, max_length=50, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='senior_profile', to='households.familymember')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoloParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=50, null=True)),
                ('educational_attainment', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('A1', 'Birth of a child as a consequence of rape'), ('A2', 'Widow/widower'), ('A3', 'Spouse of person deprived of liberty (PDL)'), ('A4', 'Spouse of person with disability (PWD)'), ('A5', 'Due to de facto separation'), ('A6', 'Due to nullity of marriage'), ('A7', 'Abandoned'), ('B1', 'Spouse of the OFW'), ('B2', 'Relative of the OFW'), ('C', 'Unmarried Person'), ('D', 'Legal guardian'), ('E', 'Relative'), ('F', 'Pregnant Woman')], max_length=10, null=True)),
                ('is_4ps_member', models.BooleanField(default=False)),
                ('is_indigenous', models.BooleanField(default=False)),
                ('is_lgbtq', models.BooleanField(default=False)),
                ('is_pwd', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_address', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_application', models.DateField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solo_parent_profile', to='households.familymember')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
