# Generated by Django 6.0 on 2026-06-30 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0004_alter_familymember_relationship_pwdprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='birthplace',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='citizenship',
            field=models.CharField(blank=True, default='Filipino', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Annulled', 'Annulled'), ('Live-in', 'Live-in')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09XXXXXXXXX' or '+639XXXXXXXXX'.", regex='^(09|\\+639)\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='familymember',
            name='education_status',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Under Graduate', 'Under Graduate')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College'), ('Post Grad', 'Post Grad'), ('Vocational', 'Vocational')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='philsys_card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='suffix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
