# Generated by Django 6.0 on 2026-06-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0005_familymember_birthplace_familymember_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soloparentprofile',
            name='monthly_income',
        ),
        migrations.AddField(
            model_name='familymember',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
