# Generated by Django 6.0 on 2026-06-30 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0006_remove_soloparentprofile_monthly_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwdprofile',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='pwdprofile',
            name='educational_attainment',
        ),
        migrations.RemoveField(
            model_name='pwdprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='seniorcitizenprofile',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='seniorcitizenprofile',
            name='educational_attainment',
        ),
        migrations.RemoveField(
            model_name='seniorcitizenprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='soloparentprofile',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='soloparentprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='soloparentprofile',
            name='educational_attainment',
        ),
        migrations.RemoveField(
            model_name='soloparentprofile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='soloparentprofile',
            name='religion',
        ),
    ]
