# Generated by Django 6.0 on 2026-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_remove_pwdprofile_civil_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='family_name',
        ),
        migrations.AddField(
            model_name='household',
            name='accessibility',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='household',
            name='flood_depth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='household',
            name='flood_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='household',
            name='hazard_exposure',
            field=models.CharField(blank=True, choices=[('NONE', 'No Hazard'), ('FLOOD', 'Flood'), ('LANDSLIDE', 'Landslide'), ('FIRE', 'Fire'), ('EARTHQUAKE', 'Earthquake/Fault'), ('RIVERBANK_EROSION', 'Riverbank Erosion'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='land_use',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'Residential'), ('AGRICULTURAL', 'Agricultural'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('INSTITUTIONAL', 'Institutional'), ('FISHING', 'Fishing')], max_length=20),
        ),
        migrations.AddField(
            model_name='household',
            name='location_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
