# Generated by Django 6.0 on 2026-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0008_remove_household_family_name_household_accessibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='hazard_other_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='household',
            name='hazard_exposure',
            field=models.CharField(choices=[('NONE', 'No Hazard'), ('FLOOD', 'Flood'), ('LANDSLIDE', 'Landslide'), ('FIRE', 'Fire'), ('EARTHQUAKE', 'Earthquake/Fault'), ('RIVERBANK_EROSION', 'Riverbank Erosion'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='household',
            name='land_use',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('AGRICULTURAL', 'Agricultural'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('INSTITUTIONAL', 'Institutional'), ('FISHING', 'Fishing')], max_length=20),
        ),
    ]
