# Generated by Django 6.0 on 2026-06-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0009_household_hazard_other_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_indigenous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_out_of_school_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_out_of_school_youth',
            field=models.BooleanField(default=False),
        ),
    ]
