# Generated by Django 6.0 on 2026-07-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0010_familymember_is_indigenous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
