# Generated by Django 6.0 on 2026-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0011_household_latitude_household_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwdprofile',
            old_name='date_issued',
            new_name='date_applied',
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='accomplished_by',
            field=models.CharField(blank=True, choices=[('APPLICANT', 'Applicant'), ('GUARDIAN', 'Guardian'), ('REPRESENTATIVE', 'Representative')], max_length=20),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='application_type',
            field=models.CharField(blank=True, choices=[('NEW', 'New Applicant'), ('RENEWAL', 'Renewal')], max_length=10),
        ),

        migrations.AddField(
            model_name='pwdprofile',
            name='employment_category',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], max_length=20),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent / Regular'), ('SEASONAL', 'Seasonal'), ('CASUAL', 'Casual'), ('EMERGENCY', 'Emergency')], max_length=20),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='gsis_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='guardian_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='guardian_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='guardian_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='organization_affiliated',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='organization_contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='organization_office_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='organization_tel_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='pagibig_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='philhealth_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='physician_license_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='psn_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pwdprofile',
            name='sss_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pwdprofile',
            name='cause_of_disability',
            field=models.CharField(blank=True, choices=[('Congenital / Inborn', [('CONGENITAL_AUTISM', 'Autism'), ('CONGENITAL_ADHD', 'ADHD'), ('CONGENITAL_CEREBRAL_PALSY', 'Cerebral Palsy'), ('CONGENITAL_DOWN_SYNDROME', 'Down Syndrome')]), ('Acquired', [('ACQUIRED_CHRONIC_ILLNESS', 'Chronic Illness'), ('ACQUIRED_CEREBRAL_PALSY', 'Cerebral Palsy'), ('ACQUIRED_INJURY', 'Injury')])], max_length=50),
        ),
        migrations.AlterField(
            model_name='pwdprofile',
            name='certifying_physician',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pwdprofile',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('DEAF_HARD_OF_HEARING', 'Deaf or Hard of Hearing'), ('INTELLECTUAL', 'Intellectual Disability'), ('LEARNING', 'Learning Disability'), ('MENTAL', 'Mental Disability'), ('PHYSICAL_ORTHOPEDIC', 'Physical Disability (Orthopedic)'), ('PSYCHOSOCIAL', 'Psychosocial Disability'), ('SPEECH_LANGUAGE', 'Speech and Language Impairment'), ('VISUAL', 'Visual Disability'), ('CANCER', 'Cancer (RA11215)'), ('RARE_DISEASE', 'Rare Disease (RA10747)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pwdprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('SELF_EMPLOYED', 'Self-employed')], max_length=20),
        ),
    ]
