# Generated by Django 6.0 on 2026-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0012_remove_pwdprofile_date_issued_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='philsys_card_no',
            new_name='government_id_number',
        ),
        migrations.AddField(
            model_name='familymember',
            name='government_id_type',
            field=models.CharField(blank=True, choices=[('PHILSYS', 'PhilSys Card'), ('PASSPORT', 'Philippine Passport'), ('DRIVERS_LICENSE', "Driver's License"), ('PHILHEALTH', 'PhilHealth ID'), ('UMID', 'UMID'), ('SSS', 'SSS ID'), ('POSTAL', 'Philippine Postal ID'), ('PRC', 'PRC ID'), ('VOTERS', "Voter's ID")], default='PHILSYS', max_length=20),
        ),
        migrations.AddField(
            model_name='seniorcitizenprofile',
            name='senior_citizen_id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
