# Generated by Django 6.0 on 2026-07-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0013_rename_philsys_card_no_familymember_government_id_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('current_wind_speed_kmh', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_precipitation_mm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('forecast_data', models.JSONField()),
                ('fetch_successful', models.BooleanField(default=True)),
            ],
        ),
    ]
