# Generated by Django 6.0 on 2026-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0017_add_family_archiving_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
