# Generated by Django 6.0 on 2026-09-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0018_familymember_date_of_death'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherSnapshot',
        ),
    ]
