# Generated by Django 6.0 on 2026-06-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AidCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_categories', to='programs.program')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('program', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], default='family', max_length=20)),
                ('minimum_age', models.PositiveIntegerField(blank=True, help_text='Leave blank if no age requirement.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aid_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='programs.aidcategory')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistances', to='programs.program')),
            ],
            options={
                'ordering': ['program', 'aid_category'],
                'unique_together': {('program', 'aid_category', 'beneficiary_type')},
            },
        ),
    ]
