# Generated by Django 6.0 on 2026-06-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='requires_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assistance',
            name='requires_solo_parent',
            field=models.BooleanField(default=False),
        ),
    ]
