# Generated by Django 6.0 on 2026-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_assistance_requires_pwd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='requires_senior_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
