# Generated by Django 6.0 on 2026-07-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_assistance_requires_senior_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='prioritization_strategy',
            field=models.CharField(choices=[('LOWEST_INCOME_FIRST', 'Lowest Income First'), ('TYPHOON_PRIORITY', 'Typhoon/Vulnerability Priority'), ('RANDOM', 'Random Among Eligible')], default='LOWEST_INCOME_FIRST', help_text='How to rank eligible beneficiaries when there are more eligible than available slots.', max_length=30),
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('INCOME_THRESHOLD', 'Income Threshold'), ('HOUSEHOLD_SIZE_INCOME', 'Household Size + Income Combination'), ('FLOOD_PRONE', 'Flood-Prone Status'), ('SPECIAL_CATEGORY', 'Special Category Membership')], max_length=30)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='programs.assistance')),
            ],
        ),
    ]
