# Generated by Django 6.0 on 2026-07-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_assistance_prioritization_strategy_eligibilityrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='aid_type',
            field=models.CharField(choices=[('CASH', 'Cash Assistance'), ('GOODS', 'Goods-in-Kind (rice, noodles, canned goods, etc.)')], default='CASH', help_text='Used by the Rotation Eligibility rule to alternate beneficiaries between cash and goods-based aid across distribution cycles.', max_length=10),
        ),
        migrations.AlterField(
            model_name='eligibilityrule',
            name='rule_type',
            field=models.CharField(choices=[('INCOME_THRESHOLD', 'Income Threshold'), ('HOUSEHOLD_SIZE_INCOME', 'Household Size + Income Combination'), ('FLOOD_PRONE', 'Flood-Prone Status'), ('SPECIAL_CATEGORY', 'Special Category Membership'), ('DAYS_SINCE_LAST_ASSISTANCE', 'Days Since Last Assistance'), ('ROTATION_ELIGIBILITY', 'Rotation Eligibility (Cash/Goods Alternation)'), ('ACTIVE_TYPHOON_SIGNAL', 'Active Typhoon Signal')], max_length=30),
        ),
    ]
