# Generated by Django 6.0 on 2026-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_assistance_aid_type_alter_eligibilityrule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_emergency_program',
            field=models.BooleanField(default=False, help_text='Emergency programs bypass 90-day cooldown and rotation eligibility rules'),
        ),
    ]
