# Generated by Django 6.0 on 2026-09-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_is_emergency_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='allows_barangay_delegation',
            field=models.BooleanField(default=False, help_text='When enabled, MSWDO Admin can delegate barangay-scoped distributions to Barangay Admins'),
        ),
    ]
