# Generated by Django 6.0 on 2026-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_allows_barangay_delegation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilityrule',
            name='rule_type',
            field=models.CharField(choices=[('INCOME_THRESHOLD', 'Income Threshold'), ('HOUSEHOLD_SIZE_INCOME', 'Household Size + Income Combination'), ('FLOOD_PRONE', 'Flood-Prone Status'), ('SPECIAL_CATEGORY', 'Special Category Membership'), ('DAYS_SINCE_LAST_ASSISTANCE', 'Days Since Last Assistance'), ('ROTATION_ELIGIBILITY', 'Rotation Eligibility (Cash/Goods Alternation)')], max_length=30),
        ),
    ]
